# -*- coding: utf-8 -*-
{   'application': False,
    'author': 'DACN QLNS SGU',
    'auto_install': False,
    'category': 'Customizations',
    'company': 'DACN QLNS SGU',
    'data': [],
    'demo': [],
    'depends': [   'base',
                   'bsi_employee_badges_and_rewards',
                   'hr',
                   'hr_appraisal',
                   'hr_attendance',
                   'hr_contract',
                   'hr_disciplinary_tracking',
                   'hr_expense',
                   'hr_holidays',
                   'hr_payroll',
                   'hr_recruitment',
                   'hr_skills',
                   'insurance_management_cybro',
                   'payroll',
                   'project',
                   'survey',
                   'website_hr_recruitment',
                   'website_slides'],
    'description': 'Module nay dung de tu dong cai cac module can thiet khi '
                   'tao database cho do an chuyen nganh quan ly nhan su Odoo.',
    'images': ['static/description/cover.svg'],
    'installable': True,
    'license': 'Other OSI approved licence',
    'live_test_url': '',
    'maintainer': 'DACN QLNS SGU',
    'name': 'DACN QLNS SGU auto-install',
    'summary': 'Auto install modules for DACN QLNS SGU',
    'version': '17.0.1.0.0',
    'website': 'https://github.com/bhbghghbgb/odoocker-dacn-qlns'}
